---
title: "Codebook for HAR Analysis Project"
date: "2026-02-19"
author: "Brian Mirkin"
output: pdf_document
---

# Introduction
This dataset is a tidy and reduced set of the data

--------------------------------------------------------------------------------

Human Activity Recognition Using Smartphones Dataset
Version 1.0

--------------------------------------------------------------------------------

Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.\
Smartlab - Non Linear Complex Systems Laboratory\
DITEN - Universit‡ degli Studi di Genova.\
Via Opera Pia 11A, I-16145, Genoa, Italy.\
activityrecognition@smartlab.ws\
www.smartlab.ws\

--------------------------------------------------------------------------------

available at 
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

Additional information about the data is available at\
https://archive.ics.uci.edu/dataset/240/human+activity+recognition+using+smartphones

# Data Description

This data is collected from accelerometer and gyroscope 3-axial signals. The
transducer is indicated in the tidy data as 'Acceleratometer' or 'Gyroscope'. Time
domain data is indicated as "timedomain" while frequency domain data is listed as
"frequencydomain" from Fast Fourier Transform output. From the original data set,
only mean and standard deviation ("std") data is kept. The axis of motion
is indicated by "-X", "-Y" and "-Z". Please see the table below for the original data
set name, new name, and whether the data was retained or not. All data is normalized
to unitless magnitude of -1 to 1.


|original_name                        |new_name                                                |retained |
|:------------------------------------|:-------------------------------------------------------|:--------|
|tBodyAcc-mean()-X                    |timedomainBodyAccelerometer-mean()-X                    |TRUE     |
|tBodyAcc-mean()-Y                    |timedomainBodyAccelerometer-mean()-Y                    |TRUE     |
|tBodyAcc-mean()-Z                    |timedomainBodyAccelerometer-mean()-Z                    |TRUE     |
|tBodyAcc-std()-X                     |timedomainBodyAccelerometer-std()-X                     |TRUE     |
|tBodyAcc-std()-Y                     |timedomainBodyAccelerometer-std()-Y                     |TRUE     |
|tBodyAcc-std()-Z                     |timedomainBodyAccelerometer-std()-Z                     |TRUE     |
|tBodyAcc-mad()-X                     |                                                        |FALSE    |
|tBodyAcc-mad()-Y                     |                                                        |FALSE    |
|tBodyAcc-mad()-Z                     |                                                        |FALSE    |
|tBodyAcc-max()-X                     |                                                        |FALSE    |
|tBodyAcc-max()-Y                     |                                                        |FALSE    |
|tBodyAcc-max()-Z                     |                                                        |FALSE    |
|tBodyAcc-min()-X                     |                                                        |FALSE    |
|tBodyAcc-min()-Y                     |                                                        |FALSE    |
|tBodyAcc-min()-Z                     |                                                        |FALSE    |
|tBodyAcc-sma()                       |                                                        |FALSE    |
|tBodyAcc-energy()-X                  |                                                        |FALSE    |
|tBodyAcc-energy()-Y                  |                                                        |FALSE    |
|tBodyAcc-energy()-Z                  |                                                        |FALSE    |
|tBodyAcc-iqr()-X                     |                                                        |FALSE    |
|tBodyAcc-iqr()-Y                     |                                                        |FALSE    |
|tBodyAcc-iqr()-Z                     |                                                        |FALSE    |
|tBodyAcc-entropy()-X                 |                                                        |FALSE    |
|tBodyAcc-entropy()-Y                 |                                                        |FALSE    |
|tBodyAcc-entropy()-Z                 |                                                        |FALSE    |
|tBodyAcc-arCoeff()-X,1               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-X,2               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-X,3               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-X,4               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Y,1               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Y,2               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Y,3               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Y,4               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Z,1               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Z,2               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Z,3               |                                                        |FALSE    |
|tBodyAcc-arCoeff()-Z,4               |                                                        |FALSE    |
|tBodyAcc-correlation()-X,Y           |                                                        |FALSE    |
|tBodyAcc-correlation()-X,Z           |                                                        |FALSE    |
|tBodyAcc-correlation()-Y,Z           |                                                        |FALSE    |
|tGravityAcc-mean()-X                 |timedomainGravityAccelerometer-mean()-X                 |TRUE     |
|tGravityAcc-mean()-Y                 |timedomainGravityAccelerometer-mean()-Y                 |TRUE     |
|tGravityAcc-mean()-Z                 |timedomainGravityAccelerometer-mean()-Z                 |TRUE     |
|tGravityAcc-std()-X                  |timedomainGravityAccelerometer-std()-X                  |TRUE     |
|tGravityAcc-std()-Y                  |timedomainGravityAccelerometer-std()-Y                  |TRUE     |
|tGravityAcc-std()-Z                  |timedomainGravityAccelerometer-std()-Z                  |TRUE     |
|tGravityAcc-mad()-X                  |                                                        |FALSE    |
|tGravityAcc-mad()-Y                  |                                                        |FALSE    |
|tGravityAcc-mad()-Z                  |                                                        |FALSE    |
|tGravityAcc-max()-X                  |                                                        |FALSE    |
|tGravityAcc-max()-Y                  |                                                        |FALSE    |
|tGravityAcc-max()-Z                  |                                                        |FALSE    |
|tGravityAcc-min()-X                  |                                                        |FALSE    |
|tGravityAcc-min()-Y                  |                                                        |FALSE    |
|tGravityAcc-min()-Z                  |                                                        |FALSE    |
|tGravityAcc-sma()                    |                                                        |FALSE    |
|tGravityAcc-energy()-X               |                                                        |FALSE    |
|tGravityAcc-energy()-Y               |                                                        |FALSE    |
|tGravityAcc-energy()-Z               |                                                        |FALSE    |
|tGravityAcc-iqr()-X                  |                                                        |FALSE    |
|tGravityAcc-iqr()-Y                  |                                                        |FALSE    |
|tGravityAcc-iqr()-Z                  |                                                        |FALSE    |
|tGravityAcc-entropy()-X              |                                                        |FALSE    |
|tGravityAcc-entropy()-Y              |                                                        |FALSE    |
|tGravityAcc-entropy()-Z              |                                                        |FALSE    |
|tGravityAcc-arCoeff()-X,1            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-X,2            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-X,3            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-X,4            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Y,1            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Y,2            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Y,3            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Y,4            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Z,1            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Z,2            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Z,3            |                                                        |FALSE    |
|tGravityAcc-arCoeff()-Z,4            |                                                        |FALSE    |
|tGravityAcc-correlation()-X,Y        |                                                        |FALSE    |
|tGravityAcc-correlation()-X,Z        |                                                        |FALSE    |
|tGravityAcc-correlation()-Y,Z        |                                                        |FALSE    |
|tBodyAccJerk-mean()-X                |timedomainBodyAccelerometerJerk-mean()-X                |TRUE     |
|tBodyAccJerk-mean()-Y                |timedomainBodyAccelerometerJerk-mean()-Y                |TRUE     |
|tBodyAccJerk-mean()-Z                |timedomainBodyAccelerometerJerk-mean()-Z                |TRUE     |
|tBodyAccJerk-std()-X                 |timedomainBodyAccelerometerJerk-std()-X                 |TRUE     |
|tBodyAccJerk-std()-Y                 |timedomainBodyAccelerometerJerk-std()-Y                 |TRUE     |
|tBodyAccJerk-std()-Z                 |timedomainBodyAccelerometerJerk-std()-Z                 |TRUE     |
|tBodyAccJerk-mad()-X                 |                                                        |FALSE    |
|tBodyAccJerk-mad()-Y                 |                                                        |FALSE    |
|tBodyAccJerk-mad()-Z                 |                                                        |FALSE    |
|tBodyAccJerk-max()-X                 |                                                        |FALSE    |
|tBodyAccJerk-max()-Y                 |                                                        |FALSE    |
|tBodyAccJerk-max()-Z                 |                                                        |FALSE    |
|tBodyAccJerk-min()-X                 |                                                        |FALSE    |
|tBodyAccJerk-min()-Y                 |                                                        |FALSE    |
|tBodyAccJerk-min()-Z                 |                                                        |FALSE    |
|tBodyAccJerk-sma()                   |                                                        |FALSE    |
|tBodyAccJerk-energy()-X              |                                                        |FALSE    |
|tBodyAccJerk-energy()-Y              |                                                        |FALSE    |
|tBodyAccJerk-energy()-Z              |                                                        |FALSE    |
|tBodyAccJerk-iqr()-X                 |                                                        |FALSE    |
|tBodyAccJerk-iqr()-Y                 |                                                        |FALSE    |
|tBodyAccJerk-iqr()-Z                 |                                                        |FALSE    |
|tBodyAccJerk-entropy()-X             |                                                        |FALSE    |
|tBodyAccJerk-entropy()-Y             |                                                        |FALSE    |
|tBodyAccJerk-entropy()-Z             |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-X,1           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-X,2           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-X,3           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-X,4           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Y,1           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Y,2           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Y,3           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Y,4           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Z,1           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Z,2           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Z,3           |                                                        |FALSE    |
|tBodyAccJerk-arCoeff()-Z,4           |                                                        |FALSE    |
|tBodyAccJerk-correlation()-X,Y       |                                                        |FALSE    |
|tBodyAccJerk-correlation()-X,Z       |                                                        |FALSE    |
|tBodyAccJerk-correlation()-Y,Z       |                                                        |FALSE    |
|tBodyGyro-mean()-X                   |timedomainBodyGyroscope-mean()-X                        |TRUE     |
|tBodyGyro-mean()-Y                   |timedomainBodyGyroscope-mean()-Y                        |TRUE     |
|tBodyGyro-mean()-Z                   |timedomainBodyGyroscope-mean()-Z                        |TRUE     |
|tBodyGyro-std()-X                    |timedomainBodyGyroscope-std()-X                         |TRUE     |
|tBodyGyro-std()-Y                    |timedomainBodyGyroscope-std()-Y                         |TRUE     |
|tBodyGyro-std()-Z                    |timedomainBodyGyroscope-std()-Z                         |TRUE     |
|tBodyGyro-mad()-X                    |                                                        |FALSE    |
|tBodyGyro-mad()-Y                    |                                                        |FALSE    |
|tBodyGyro-mad()-Z                    |                                                        |FALSE    |
|tBodyGyro-max()-X                    |                                                        |FALSE    |
|tBodyGyro-max()-Y                    |                                                        |FALSE    |
|tBodyGyro-max()-Z                    |                                                        |FALSE    |
|tBodyGyro-min()-X                    |                                                        |FALSE    |
|tBodyGyro-min()-Y                    |                                                        |FALSE    |
|tBodyGyro-min()-Z                    |                                                        |FALSE    |
|tBodyGyro-sma()                      |                                                        |FALSE    |
|tBodyGyro-energy()-X                 |                                                        |FALSE    |
|tBodyGyro-energy()-Y                 |                                                        |FALSE    |
|tBodyGyro-energy()-Z                 |                                                        |FALSE    |
|tBodyGyro-iqr()-X                    |                                                        |FALSE    |
|tBodyGyro-iqr()-Y                    |                                                        |FALSE    |
|tBodyGyro-iqr()-Z                    |                                                        |FALSE    |
|tBodyGyro-entropy()-X                |                                                        |FALSE    |
|tBodyGyro-entropy()-Y                |                                                        |FALSE    |
|tBodyGyro-entropy()-Z                |                                                        |FALSE    |
|tBodyGyro-arCoeff()-X,1              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-X,2              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-X,3              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-X,4              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Y,1              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Y,2              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Y,3              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Y,4              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Z,1              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Z,2              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Z,3              |                                                        |FALSE    |
|tBodyGyro-arCoeff()-Z,4              |                                                        |FALSE    |
|tBodyGyro-correlation()-X,Y          |                                                        |FALSE    |
|tBodyGyro-correlation()-X,Z          |                                                        |FALSE    |
|tBodyGyro-correlation()-Y,Z          |                                                        |FALSE    |
|tBodyGyroJerk-mean()-X               |timedomainBodyGyroscopeJerk-mean()-X                    |TRUE     |
|tBodyGyroJerk-mean()-Y               |timedomainBodyGyroscopeJerk-mean()-Y                    |TRUE     |
|tBodyGyroJerk-mean()-Z               |timedomainBodyGyroscopeJerk-mean()-Z                    |TRUE     |
|tBodyGyroJerk-std()-X                |timedomainBodyGyroscopeJerk-std()-X                     |TRUE     |
|tBodyGyroJerk-std()-Y                |timedomainBodyGyroscopeJerk-std()-Y                     |TRUE     |
|tBodyGyroJerk-std()-Z                |timedomainBodyGyroscopeJerk-std()-Z                     |TRUE     |
|tBodyGyroJerk-mad()-X                |                                                        |FALSE    |
|tBodyGyroJerk-mad()-Y                |                                                        |FALSE    |
|tBodyGyroJerk-mad()-Z                |                                                        |FALSE    |
|tBodyGyroJerk-max()-X                |                                                        |FALSE    |
|tBodyGyroJerk-max()-Y                |                                                        |FALSE    |
|tBodyGyroJerk-max()-Z                |                                                        |FALSE    |
|tBodyGyroJerk-min()-X                |                                                        |FALSE    |
|tBodyGyroJerk-min()-Y                |                                                        |FALSE    |
|tBodyGyroJerk-min()-Z                |                                                        |FALSE    |
|tBodyGyroJerk-sma()                  |                                                        |FALSE    |
|tBodyGyroJerk-energy()-X             |                                                        |FALSE    |
|tBodyGyroJerk-energy()-Y             |                                                        |FALSE    |
|tBodyGyroJerk-energy()-Z             |                                                        |FALSE    |
|tBodyGyroJerk-iqr()-X                |                                                        |FALSE    |
|tBodyGyroJerk-iqr()-Y                |                                                        |FALSE    |
|tBodyGyroJerk-iqr()-Z                |                                                        |FALSE    |
|tBodyGyroJerk-entropy()-X            |                                                        |FALSE    |
|tBodyGyroJerk-entropy()-Y            |                                                        |FALSE    |
|tBodyGyroJerk-entropy()-Z            |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-X,1          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-X,2          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-X,3          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-X,4          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Y,1          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Y,2          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Y,3          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Y,4          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Z,1          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Z,2          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Z,3          |                                                        |FALSE    |
|tBodyGyroJerk-arCoeff()-Z,4          |                                                        |FALSE    |
|tBodyGyroJerk-correlation()-X,Y      |                                                        |FALSE    |
|tBodyGyroJerk-correlation()-X,Z      |                                                        |FALSE    |
|tBodyGyroJerk-correlation()-Y,Z      |                                                        |FALSE    |
|tBodyAccMag-mean()                   |timedomainBodyAccelerometerMag-mean()                   |TRUE     |
|tBodyAccMag-std()                    |timedomainBodyAccelerometerMag-std()                    |TRUE     |
|tBodyAccMag-mad()                    |                                                        |FALSE    |
|tBodyAccMag-max()                    |                                                        |FALSE    |
|tBodyAccMag-min()                    |                                                        |FALSE    |
|tBodyAccMag-sma()                    |                                                        |FALSE    |
|tBodyAccMag-energy()                 |                                                        |FALSE    |
|tBodyAccMag-iqr()                    |                                                        |FALSE    |
|tBodyAccMag-entropy()                |                                                        |FALSE    |
|tBodyAccMag-arCoeff()1               |                                                        |FALSE    |
|tBodyAccMag-arCoeff()2               |                                                        |FALSE    |
|tBodyAccMag-arCoeff()3               |                                                        |FALSE    |
|tBodyAccMag-arCoeff()4               |                                                        |FALSE    |
|tGravityAccMag-mean()                |timedomainGravityAccelerometerMag-mean()                |TRUE     |
|tGravityAccMag-std()                 |timedomainGravityAccelerometerMag-std()                 |TRUE     |
|tGravityAccMag-mad()                 |                                                        |FALSE    |
|tGravityAccMag-max()                 |                                                        |FALSE    |
|tGravityAccMag-min()                 |                                                        |FALSE    |
|tGravityAccMag-sma()                 |                                                        |FALSE    |
|tGravityAccMag-energy()              |                                                        |FALSE    |
|tGravityAccMag-iqr()                 |                                                        |FALSE    |
|tGravityAccMag-entropy()             |                                                        |FALSE    |
|tGravityAccMag-arCoeff()1            |                                                        |FALSE    |
|tGravityAccMag-arCoeff()2            |                                                        |FALSE    |
|tGravityAccMag-arCoeff()3            |                                                        |FALSE    |
|tGravityAccMag-arCoeff()4            |                                                        |FALSE    |
|tBodyAccJerkMag-mean()               |timedomainBodyAccelerometerJerkMag-mean()               |TRUE     |
|tBodyAccJerkMag-std()                |timedomainBodyAccelerometerJerkMag-std()                |TRUE     |
|tBodyAccJerkMag-mad()                |                                                        |FALSE    |
|tBodyAccJerkMag-max()                |                                                        |FALSE    |
|tBodyAccJerkMag-min()                |                                                        |FALSE    |
|tBodyAccJerkMag-sma()                |                                                        |FALSE    |
|tBodyAccJerkMag-energy()             |                                                        |FALSE    |
|tBodyAccJerkMag-iqr()                |                                                        |FALSE    |
|tBodyAccJerkMag-entropy()            |                                                        |FALSE    |
|tBodyAccJerkMag-arCoeff()1           |                                                        |FALSE    |
|tBodyAccJerkMag-arCoeff()2           |                                                        |FALSE    |
|tBodyAccJerkMag-arCoeff()3           |                                                        |FALSE    |
|tBodyAccJerkMag-arCoeff()4           |                                                        |FALSE    |
|tBodyGyroMag-mean()                  |timedomainBodyGyroscopeMag-mean()                       |TRUE     |
|tBodyGyroMag-std()                   |timedomainBodyGyroscopeMag-std()                        |TRUE     |
|tBodyGyroMag-mad()                   |                                                        |FALSE    |
|tBodyGyroMag-max()                   |                                                        |FALSE    |
|tBodyGyroMag-min()                   |                                                        |FALSE    |
|tBodyGyroMag-sma()                   |                                                        |FALSE    |
|tBodyGyroMag-energy()                |                                                        |FALSE    |
|tBodyGyroMag-iqr()                   |                                                        |FALSE    |
|tBodyGyroMag-entropy()               |                                                        |FALSE    |
|tBodyGyroMag-arCoeff()1              |                                                        |FALSE    |
|tBodyGyroMag-arCoeff()2              |                                                        |FALSE    |
|tBodyGyroMag-arCoeff()3              |                                                        |FALSE    |
|tBodyGyroMag-arCoeff()4              |                                                        |FALSE    |
|tBodyGyroJerkMag-mean()              |timedomainBodyGyroscopeJerkMag-mean()                   |TRUE     |
|tBodyGyroJerkMag-std()               |timedomainBodyGyroscopeJerkMag-std()                    |TRUE     |
|tBodyGyroJerkMag-mad()               |                                                        |FALSE    |
|tBodyGyroJerkMag-max()               |                                                        |FALSE    |
|tBodyGyroJerkMag-min()               |                                                        |FALSE    |
|tBodyGyroJerkMag-sma()               |                                                        |FALSE    |
|tBodyGyroJerkMag-energy()            |                                                        |FALSE    |
|tBodyGyroJerkMag-iqr()               |                                                        |FALSE    |
|tBodyGyroJerkMag-entropy()           |                                                        |FALSE    |
|tBodyGyroJerkMag-arCoeff()1          |                                                        |FALSE    |
|tBodyGyroJerkMag-arCoeff()2          |                                                        |FALSE    |
|tBodyGyroJerkMag-arCoeff()3          |                                                        |FALSE    |
|tBodyGyroJerkMag-arCoeff()4          |                                                        |FALSE    |
|fBodyAcc-mean()-X                    |freqdomainBodyAccelerometer-mean()-X                    |TRUE     |
|fBodyAcc-mean()-Y                    |freqdomainBodyAccelerometer-mean()-Y                    |TRUE     |
|fBodyAcc-mean()-Z                    |freqdomainBodyAccelerometer-mean()-Z                    |TRUE     |
|fBodyAcc-std()-X                     |freqdomainBodyAccelerometer-std()-X                     |TRUE     |
|fBodyAcc-std()-Y                     |freqdomainBodyAccelerometer-std()-Y                     |TRUE     |
|fBodyAcc-std()-Z                     |freqdomainBodyAccelerometer-std()-Z                     |TRUE     |
|fBodyAcc-mad()-X                     |                                                        |FALSE    |
|fBodyAcc-mad()-Y                     |                                                        |FALSE    |
|fBodyAcc-mad()-Z                     |                                                        |FALSE    |
|fBodyAcc-max()-X                     |                                                        |FALSE    |
|fBodyAcc-max()-Y                     |                                                        |FALSE    |
|fBodyAcc-max()-Z                     |                                                        |FALSE    |
|fBodyAcc-min()-X                     |                                                        |FALSE    |
|fBodyAcc-min()-Y                     |                                                        |FALSE    |
|fBodyAcc-min()-Z                     |                                                        |FALSE    |
|fBodyAcc-sma()                       |                                                        |FALSE    |
|fBodyAcc-energy()-X                  |                                                        |FALSE    |
|fBodyAcc-energy()-Y                  |                                                        |FALSE    |
|fBodyAcc-energy()-Z                  |                                                        |FALSE    |
|fBodyAcc-iqr()-X                     |                                                        |FALSE    |
|fBodyAcc-iqr()-Y                     |                                                        |FALSE    |
|fBodyAcc-iqr()-Z                     |                                                        |FALSE    |
|fBodyAcc-entropy()-X                 |                                                        |FALSE    |
|fBodyAcc-entropy()-Y                 |                                                        |FALSE    |
|fBodyAcc-entropy()-Z                 |                                                        |FALSE    |
|fBodyAcc-maxInds-X                   |                                                        |FALSE    |
|fBodyAcc-maxInds-Y                   |                                                        |FALSE    |
|fBodyAcc-maxInds-Z                   |                                                        |FALSE    |
|fBodyAcc-meanFreq()-X                |freqdomainBodyAccelerometer-meanFreq()-X                |TRUE     |
|fBodyAcc-meanFreq()-Y                |freqdomainBodyAccelerometer-meanFreq()-Y                |TRUE     |
|fBodyAcc-meanFreq()-Z                |freqdomainBodyAccelerometer-meanFreq()-Z                |TRUE     |
|fBodyAcc-skewness()-X                |                                                        |FALSE    |
|fBodyAcc-kurtosis()-X                |                                                        |FALSE    |
|fBodyAcc-skewness()-Y                |                                                        |FALSE    |
|fBodyAcc-kurtosis()-Y                |                                                        |FALSE    |
|fBodyAcc-skewness()-Z                |                                                        |FALSE    |
|fBodyAcc-kurtosis()-Z                |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,8           |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-9,16          |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-17,24         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-25,32         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-33,40         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-41,48         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-49,56         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-57,64         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,16          |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-17,32         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-33,48         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-49,64         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,24          |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-25,48         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,8_1         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-9,16_1        |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-17,24_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-25,32_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-33,40_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-41,48_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-49,56_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-57,64_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,16_1        |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-17,32_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-33,48_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-49,64_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,24_1        |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-25,48_1       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,8_2         |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-9,16_2        |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-17,24_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-25,32_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-33,40_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-41,48_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-49,56_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-57,64_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,16_2        |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-17,32_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-33,48_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-49,64_2       |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-1,24_2        |                                                        |FALSE    |
|fBodyAcc-bandsEnergy()-25,48_2       |                                                        |FALSE    |
|fBodyAccJerk-mean()-X                |freqdomainBodyAccelerometerJerk-mean()-X                |TRUE     |
|fBodyAccJerk-mean()-Y                |freqdomainBodyAccelerometerJerk-mean()-Y                |TRUE     |
|fBodyAccJerk-mean()-Z                |freqdomainBodyAccelerometerJerk-mean()-Z                |TRUE     |
|fBodyAccJerk-std()-X                 |freqdomainBodyAccelerometerJerk-std()-X                 |TRUE     |
|fBodyAccJerk-std()-Y                 |freqdomainBodyAccelerometerJerk-std()-Y                 |TRUE     |
|fBodyAccJerk-std()-Z                 |freqdomainBodyAccelerometerJerk-std()-Z                 |TRUE     |
|fBodyAccJerk-mad()-X                 |                                                        |FALSE    |
|fBodyAccJerk-mad()-Y                 |                                                        |FALSE    |
|fBodyAccJerk-mad()-Z                 |                                                        |FALSE    |
|fBodyAccJerk-max()-X                 |                                                        |FALSE    |
|fBodyAccJerk-max()-Y                 |                                                        |FALSE    |
|fBodyAccJerk-max()-Z                 |                                                        |FALSE    |
|fBodyAccJerk-min()-X                 |                                                        |FALSE    |
|fBodyAccJerk-min()-Y                 |                                                        |FALSE    |
|fBodyAccJerk-min()-Z                 |                                                        |FALSE    |
|fBodyAccJerk-sma()                   |                                                        |FALSE    |
|fBodyAccJerk-energy()-X              |                                                        |FALSE    |
|fBodyAccJerk-energy()-Y              |                                                        |FALSE    |
|fBodyAccJerk-energy()-Z              |                                                        |FALSE    |
|fBodyAccJerk-iqr()-X                 |                                                        |FALSE    |
|fBodyAccJerk-iqr()-Y                 |                                                        |FALSE    |
|fBodyAccJerk-iqr()-Z                 |                                                        |FALSE    |
|fBodyAccJerk-entropy()-X             |                                                        |FALSE    |
|fBodyAccJerk-entropy()-Y             |                                                        |FALSE    |
|fBodyAccJerk-entropy()-Z             |                                                        |FALSE    |
|fBodyAccJerk-maxInds-X               |                                                        |FALSE    |
|fBodyAccJerk-maxInds-Y               |                                                        |FALSE    |
|fBodyAccJerk-maxInds-Z               |                                                        |FALSE    |
|fBodyAccJerk-meanFreq()-X            |freqdomainBodyAccelerometerJerk-meanFreq()-X            |TRUE     |
|fBodyAccJerk-meanFreq()-Y            |freqdomainBodyAccelerometerJerk-meanFreq()-Y            |TRUE     |
|fBodyAccJerk-meanFreq()-Z            |freqdomainBodyAccelerometerJerk-meanFreq()-Z            |TRUE     |
|fBodyAccJerk-skewness()-X            |                                                        |FALSE    |
|fBodyAccJerk-kurtosis()-X            |                                                        |FALSE    |
|fBodyAccJerk-skewness()-Y            |                                                        |FALSE    |
|fBodyAccJerk-kurtosis()-Y            |                                                        |FALSE    |
|fBodyAccJerk-skewness()-Z            |                                                        |FALSE    |
|fBodyAccJerk-kurtosis()-Z            |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,8       |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-9,16      |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-17,24     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-25,32     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-33,40     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-41,48     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-49,56     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-57,64     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,16      |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-17,32     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-33,48     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-49,64     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,24      |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-25,48     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,8_1     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-9,16_1    |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-17,24_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-25,32_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-33,40_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-41,48_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-49,56_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-57,64_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,16_1    |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-17,32_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-33,48_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-49,64_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,24_1    |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-25,48_1   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,8_2     |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-9,16_2    |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-17,24_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-25,32_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-33,40_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-41,48_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-49,56_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-57,64_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,16_2    |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-17,32_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-33,48_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-49,64_2   |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-1,24_2    |                                                        |FALSE    |
|fBodyAccJerk-bandsEnergy()-25,48_2   |                                                        |FALSE    |
|fBodyGyro-mean()-X                   |freqdomainBodyGyroscope-mean()-X                        |TRUE     |
|fBodyGyro-mean()-Y                   |freqdomainBodyGyroscope-mean()-Y                        |TRUE     |
|fBodyGyro-mean()-Z                   |freqdomainBodyGyroscope-mean()-Z                        |TRUE     |
|fBodyGyro-std()-X                    |freqdomainBodyGyroscope-std()-X                         |TRUE     |
|fBodyGyro-std()-Y                    |freqdomainBodyGyroscope-std()-Y                         |TRUE     |
|fBodyGyro-std()-Z                    |freqdomainBodyGyroscope-std()-Z                         |TRUE     |
|fBodyGyro-mad()-X                    |                                                        |FALSE    |
|fBodyGyro-mad()-Y                    |                                                        |FALSE    |
|fBodyGyro-mad()-Z                    |                                                        |FALSE    |
|fBodyGyro-max()-X                    |                                                        |FALSE    |
|fBodyGyro-max()-Y                    |                                                        |FALSE    |
|fBodyGyro-max()-Z                    |                                                        |FALSE    |
|fBodyGyro-min()-X                    |                                                        |FALSE    |
|fBodyGyro-min()-Y                    |                                                        |FALSE    |
|fBodyGyro-min()-Z                    |                                                        |FALSE    |
|fBodyGyro-sma()                      |                                                        |FALSE    |
|fBodyGyro-energy()-X                 |                                                        |FALSE    |
|fBodyGyro-energy()-Y                 |                                                        |FALSE    |
|fBodyGyro-energy()-Z                 |                                                        |FALSE    |
|fBodyGyro-iqr()-X                    |                                                        |FALSE    |
|fBodyGyro-iqr()-Y                    |                                                        |FALSE    |
|fBodyGyro-iqr()-Z                    |                                                        |FALSE    |
|fBodyGyro-entropy()-X                |                                                        |FALSE    |
|fBodyGyro-entropy()-Y                |                                                        |FALSE    |
|fBodyGyro-entropy()-Z                |                                                        |FALSE    |
|fBodyGyro-maxInds-X                  |                                                        |FALSE    |
|fBodyGyro-maxInds-Y                  |                                                        |FALSE    |
|fBodyGyro-maxInds-Z                  |                                                        |FALSE    |
|fBodyGyro-meanFreq()-X               |freqdomainBodyGyroscope-meanFreq()-X                    |TRUE     |
|fBodyGyro-meanFreq()-Y               |freqdomainBodyGyroscope-meanFreq()-Y                    |TRUE     |
|fBodyGyro-meanFreq()-Z               |freqdomainBodyGyroscope-meanFreq()-Z                    |TRUE     |
|fBodyGyro-skewness()-X               |                                                        |FALSE    |
|fBodyGyro-kurtosis()-X               |                                                        |FALSE    |
|fBodyGyro-skewness()-Y               |                                                        |FALSE    |
|fBodyGyro-kurtosis()-Y               |                                                        |FALSE    |
|fBodyGyro-skewness()-Z               |                                                        |FALSE    |
|fBodyGyro-kurtosis()-Z               |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,8          |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-9,16         |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-17,24        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-25,32        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-33,40        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-41,48        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-49,56        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-57,64        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,16         |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-17,32        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-33,48        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-49,64        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,24         |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-25,48        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,8_1        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-9,16_1       |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-17,24_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-25,32_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-33,40_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-41,48_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-49,56_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-57,64_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,16_1       |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-17,32_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-33,48_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-49,64_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,24_1       |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-25,48_1      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,8_2        |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-9,16_2       |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-17,24_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-25,32_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-33,40_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-41,48_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-49,56_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-57,64_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,16_2       |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-17,32_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-33,48_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-49,64_2      |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-1,24_2       |                                                        |FALSE    |
|fBodyGyro-bandsEnergy()-25,48_2      |                                                        |FALSE    |
|fBodyAccMag-mean()                   |freqdomainBodyAccelerometerMag-mean()                   |TRUE     |
|fBodyAccMag-std()                    |freqdomainBodyAccelerometerMag-std()                    |TRUE     |
|fBodyAccMag-mad()                    |                                                        |FALSE    |
|fBodyAccMag-max()                    |                                                        |FALSE    |
|fBodyAccMag-min()                    |                                                        |FALSE    |
|fBodyAccMag-sma()                    |                                                        |FALSE    |
|fBodyAccMag-energy()                 |                                                        |FALSE    |
|fBodyAccMag-iqr()                    |                                                        |FALSE    |
|fBodyAccMag-entropy()                |                                                        |FALSE    |
|fBodyAccMag-maxInds                  |                                                        |FALSE    |
|fBodyAccMag-meanFreq()               |freqdomainBodyAccelerometerMag-meanFreq()               |TRUE     |
|fBodyAccMag-skewness()               |                                                        |FALSE    |
|fBodyAccMag-kurtosis()               |                                                        |FALSE    |
|fBodyBodyAccJerkMag-mean()           |freqdomainBodyBodyAccelerometerJerkMag-mean()           |TRUE     |
|fBodyBodyAccJerkMag-std()            |freqdomainBodyBodyAccelerometerJerkMag-std()            |TRUE     |
|fBodyBodyAccJerkMag-mad()            |                                                        |FALSE    |
|fBodyBodyAccJerkMag-max()            |                                                        |FALSE    |
|fBodyBodyAccJerkMag-min()            |                                                        |FALSE    |
|fBodyBodyAccJerkMag-sma()            |                                                        |FALSE    |
|fBodyBodyAccJerkMag-energy()         |                                                        |FALSE    |
|fBodyBodyAccJerkMag-iqr()            |                                                        |FALSE    |
|fBodyBodyAccJerkMag-entropy()        |                                                        |FALSE    |
|fBodyBodyAccJerkMag-maxInds          |                                                        |FALSE    |
|fBodyBodyAccJerkMag-meanFreq()       |freqdomainBodyBodyAccelerometerJerkMag-meanFreq()       |TRUE     |
|fBodyBodyAccJerkMag-skewness()       |                                                        |FALSE    |
|fBodyBodyAccJerkMag-kurtosis()       |                                                        |FALSE    |
|fBodyBodyGyroMag-mean()              |freqdomainBodyBodyGyroscopeMag-mean()                   |TRUE     |
|fBodyBodyGyroMag-std()               |freqdomainBodyBodyGyroscopeMag-std()                    |TRUE     |
|fBodyBodyGyroMag-mad()               |                                                        |FALSE    |
|fBodyBodyGyroMag-max()               |                                                        |FALSE    |
|fBodyBodyGyroMag-min()               |                                                        |FALSE    |
|fBodyBodyGyroMag-sma()               |                                                        |FALSE    |
|fBodyBodyGyroMag-energy()            |                                                        |FALSE    |
|fBodyBodyGyroMag-iqr()               |                                                        |FALSE    |
|fBodyBodyGyroMag-entropy()           |                                                        |FALSE    |
|fBodyBodyGyroMag-maxInds             |                                                        |FALSE    |
|fBodyBodyGyroMag-meanFreq()          |freqdomainBodyBodyGyroscopeMag-meanFreq()               |TRUE     |
|fBodyBodyGyroMag-skewness()          |                                                        |FALSE    |
|fBodyBodyGyroMag-kurtosis()          |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-mean()          |freqdomainBodyBodyGyroscopeJerkMag-mean()               |TRUE     |
|fBodyBodyGyroJerkMag-std()           |freqdomainBodyBodyGyroscopeJerkMag-std()                |TRUE     |
|fBodyBodyGyroJerkMag-mad()           |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-max()           |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-min()           |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-sma()           |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-energy()        |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-iqr()           |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-entropy()       |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-maxInds         |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-meanFreq()      |freqdomainBodyBodyGyroscopeJerkMag-meanFreq()           |TRUE     |
|fBodyBodyGyroJerkMag-skewness()      |                                                        |FALSE    |
|fBodyBodyGyroJerkMag-kurtosis()      |                                                        |FALSE    |
|angle(tBodyAccMean,gravity)          |angle(timedomainBodyAccelerometerMean,gravity)          |TRUE     |
|angle(tBodyAccJerkMean),gravityMean) |angle(timedomainBodyAccelerometerJerkMean),gravityMean) |TRUE     |
|angle(tBodyGyroMean,gravityMean)     |angle(timedomainBodyGyroscopeMean,gravityMean)          |TRUE     |
|angle(tBodyGyroJerkMean,gravityMean) |angle(timedomainBodyGyroscopeJerkMean,gravityMean)      |TRUE     |
|angle(X,gravityMean)                 |angle(X,gravityMean)                                    |TRUE     |
|angle(Y,gravityMean)                 |angle(Y,gravityMean)                                    |TRUE     |
|angle(Z,gravityMean)                 |angle(Z,gravityMean)                                    |TRUE     |

# Study design

Please see the original data set for links to more information about this study.